// Generated by Dagger (https://dagger.dev).
package com.valdosz.pokemon_list.di.module;

import com.valdosz.pokemon_list.model.api.PokemonAPI;
import dagger.internal.Factory;
import dagger.internal.Preconditions;

@SuppressWarnings({
        "unchecked",
        "rawtypes"
})
public final class AppModule_PokemonAPIFactory implements Factory<PokemonAPI> {
    private final AppModule module;

    public AppModule_PokemonAPIFactory(AppModule module) {
        this.module = module;
    }

    @Override
    public PokemonAPI get() {
        return pokemonAPI(module);
    }

    public static AppModule_PokemonAPIFactory create(AppModule module) {
        return new AppModule_PokemonAPIFactory(module);
    }

    public static PokemonAPI pokemonAPI(AppModule instance) {
        return Preconditions.checkNotNullFromProvides(instance.pokemonAPI());
    }
}
